version: '3'
services:
  two57-mysql:
    container_name: two57-mysql
    image: mysql/mysql-server:5.7
    volumes:
      # Pass volume named mysql-data to mysql container
      - "~/mysql-data:/var/lib/mysql"
    environment:
      MYSQL_DATABASE: test
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_ROOT_HOST: '%'
    ports:
      - "13306:3306"
    restart: always

  app:
    build: .
    volumes:
      - .:/app
      - ~/.m2:/root/.m2
    working_dir: /app
    ports:
      - 8080:8080
    command: mvn clean spring-boot:run
    depends_on:
      - two57-mysql


